# CI de Nivel 01 - Disparo manual a partir de 1 clique

# nome do nosso 'pipeline'
name: 'Execução Manual com Reporting'

# regras de disparo, gatilhos ou triggers
# gatilho de execução manual = workflow_dispatch
on:
  workflow_dispatch:

  #tarefas que sao executadas dentro dos pipelines sao jobs
jobs:
  e2e-tests:
    #maquina que o job vai executar
    runs-on: ubuntu-latest

    #passos para o script de build
    steps:
      #clone do projeto
      - uses: actions/checkout@v4

      #instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      # instalação do yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalando dependências
      - name: Instalando dependências
        run: yarn

      # instalando Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      # executor de testes e2e
      - name: Executando testes e2e
        run: yarn run e2e

      # agora com o report ao final
      - name: Test Reporter
        uses: dorny/test-reporter@v2.1.0
