  # CI de Nivel 03 - Disparo automático a partir de um deploy

  # nome do nosso 'pipeline'
  name: 'Execução por Deploy'

  # regras de disparo, gatilhos ou triggers
  # gatilho de execução a partir de outro pipeline = workflow_run
  on:
    workflow_run:
      workflows: ['Execução Manual']
      types:
        - completed

    #tarefas que sao executadas dentro dos pipelines sao jobs
  jobs:
    e2e-tests:

      #maquina que o job vai executar
      runs-on: ubuntu-latest

      #condicional if
      #'${ expressao }'

      # se o status de conclusao do pipeline de origem foi de sucesso, ele prossegue aos demais steps
      if: ${{ github.event.workflow_run.conclusion == 'success' }}

      #passos para o script de build
      steps:
        #clone do projeto
        - uses: actions/checkout@v4

        #instalação do node
        - uses: actions/setup-node@v4
          with:
            node-version: latest


        # instalação do yarn
        - name: Instalando Yarn
          run: npm install -g yarn

        # instalando dependências
        - name: Instalando dependências
          run: yarn

        # instalando Playwright
        - name: Instalando Playwright
          run: yarn playwright install

        # executor de testes e2e
        - name: Executando testes e2e
          run: yarn run e2e  
