# CI de Nivel 04 - Disparo dostestes dentro do pipeline de dev

# nome do nosso 'pipeline'
name: 'Execução Integrada a Dev'

on:
  workflow_dispatch:

jobs:
  inspecao:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando Dependências
        run: yarn

      - name: Checando padronização do código
        run: yarn lint

  unidade:
    runs-on: ubuntu-latest
    #needs: [] #nao depende de nenhum anterior

    steps:
      - uses: actions/checkout@v4
      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando Dependências
        run: yarn

      - name: Executando testes de unidade
        run: yarn test

  e2e-tests:
    runs-on: ubuntu-latest
    needs: [unidade]

    steps:
      #clone do projeto
      - uses: actions/checkout@v4

      #instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      # instalação do yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalando dependências
      - name: Instalando dependências
        run: yarn

      # instalando Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      # executor de testes e2e
      - name: Executando testes e2e
        run: yarn run e2e

        # upload de arquivos
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        # if: ${{ always() }}
        with:
          name: relatorio
          path: ./playwright-report

  mutacao:
    runs-on: ubuntu-latest
    needs: [unidade]

    steps:
      #clone do projeto
      - uses: actions/checkout@v4

      #instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      # instalação do yarn
      - name: Instalando Yarn
        run: npm install -g yarn

      # instalando dependências
      - name: Instalando dependências
        run: yarn

      # instalando Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      # executor de testes e2e
      - name: Executando testes de mutação
        run:
          yarn run test:mutation

          # upload de arquivos
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        # if: ${{ always() }}
        with:
          name: relatorio-mutation
          path: ./reports/mutation

  deploy:
    runs-on: ubuntu-latest
    needs: [e2e-tests, inspecao]

    steps:
      - name: Executando testes de mutação
        run: echo "Simulando Deploy"
